#!/usr/bin/env bash
if [ ! -d .git.versioned ]; then
  if [ $0 == x"post-receive" ]; then
    # We are running on server and should update scripts"
    PREV=$(pwd)
    TMP=$(mktemp -d)
    cd $TMP
    git clone $PREV fullrepos > /dev/null
    cp fullrepos/.git.versioned/hooks/* $PREV/hooks/
    chmod u+x $PREV/hooks/*
    cd $PREV
    rm -rf $TMP
  fi
  test -f $0 && $0.server
else
  if [ x$0 == x"pre-commit" ]; then
    echo "Pre commit"
    cp .git.versioned/hooks/* .git/hooks/
    chmod u+x $PREV/hooks/*
  fi
  test -f $0.client && $0.client
fi
exit 0
